// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Provide a helpful runtime guard so the app doesn't crash with an opaque error
// if the Vite environment variables are not present at build/runtime.
import type { SupabaseClient } from '@supabase/supabase-js';

const MISSING_ENV_MESSAGE =
  'Supabase environment variables VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are required.\n' +
  'Add them to a root .env file (or export them) and restart the dev server.';

function createMissingProxy(): SupabaseClient<Database> {
  const handler: ProxyHandler<Record<string, unknown>> = {
    get() {
      return () => {
        throw new Error(MISSING_ENV_MESSAGE);
      };
    }
  };
  return new Proxy({}, handler) as unknown as SupabaseClient<Database>;
}

export const supabase: SupabaseClient<Database> = (() => {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    // Log a clear error for developers and export a proxy that throws when used
    console.error(MISSING_ENV_MESSAGE);
    return createMissingProxy();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
})();